"""End-to-end selftest: generate a sample tender PDF with known facts, run the
full pipeline against the real API, and verify the results.

Run: python main.py --selftest   (makes one real DeepSeek API call; cost is
negligible). Console output stays in Chinese for the user running it.
"""
import os
import sys
import tempfile

SAMPLE_PAGE1 = """XX市市政管网改造工程监理招标公告

1. 项目概况与招标范围
1.1 项目名称：XX市市政管网改造工程监理
1.2 建设地点：XX市高新区
1.3 计划工期：540 日历天
1.4 招标范围：施工阶段全过程监理服务

2. 投标人资格要求
2.1 投标人须具备建设行政主管部门核发的市政公用工程监理乙级及以上资质
2.2 拟派项目总监须具有注册监理工程师注册执业证书，且近三年内无不良行为记录
2.3 投标人近三年（2023年至今）须至少完成1项类似市政监理业绩
2.4 本项目不接受联合体投标
"""

SAMPLE_PAGE2 = """3. 商务要求
3.1 本项目最高投标限价为：380万元，投标报价超出最高限价的，其投标将被否决
3.2 投标保证金金额为人民币5万元整，须于2026年9月10日17时前到达指定账户
3.3 付款方式：按监理服务期分四次平均支付，验收合格后支付尾款
3.4 监理服务期限自开工令下发之日起至工程缺陷责任期期满止

4. 投标文件递交及开标时间
4.1 投标截止时间（开标时间）：2026年9月15日09时30分（北京时间）
4.2 递交地点：XX市公共资源交易中心第三开标厅
4.3 澄清问题的截止时间：2026年9月1日17时00分
4.4 逾期送达或不符合密封要求的投标文件，招标人不予受理
"""

SAMPLE_PAGE3 = """5. 废标条款（下列情况之一的，作无效标处理）
5.1 未按要求密封、标记投标文件的
5.2 投标报价高于最高投标限价的
5.3 投标人不满足资格要求的
5.4 未按规定提交投标保证金的
5.5 投标文件未按规定签字盖章的
5.6 投标有效期不足90天的

6. 评分办法（总分100分）
6.1 技术标（40分）：监理大纲20分、人员配备10分、检测设备与手段10分
6.2 商务标（60分）：投标报价55分（以有效投标报价最低价为基准价）、企业业绩5分
6.3 评标委员会按得分由高到低推荐3名中标候选人

7. 技术要求
7.1 现场监理人员配备不少于5人，专业应覆盖市政给排水、道路工程
7.2 监理大纲应包含质量控制、进度控制、安全文明施工管理措施
"""

# Selftest assertions: keywords each category must hit at least once.
EXPECTED = {
    "资质要求": ["乙级"],
    "商务要求": ["380"],
    "技术要求": ["5人"],
    "时间节点": ["9月15日"],
    "废标项": ["密封"],
    "评分标准": ["40"],
}


def make_sample_pdf(path):
    import pymupdf

    doc = pymupdf.open()
    for text in (SAMPLE_PAGE1, SAMPLE_PAGE2, SAMPLE_PAGE3):
        page = doc.new_page()  # A4 default size
        page.insert_textbox(
            pymupdf.Rect(50, 60, 545, 780), text,
            fontname="china-s", fontsize=11, lineheight=1.6,
        )
    doc.save(path)
    doc.close()


def run_selftest():
    from bidbrief.config import load_config
    from bidbrief.parser import parse_file
    from bidbrief.pipeline import run_and_export

    cfg = load_config()
    if not cfg.get("api_key"):
        print("[SELFTEST FAIL] config.json 缺少 api_key")
        return False

    tmp = tempfile.mkdtemp(prefix="bidbrief_selftest_")
    pdf = os.path.join(tmp, "样例招标文件.pdf")
    make_sample_pdf(pdf)
    print(f"样例PDF已生成：{pdf}")

    parsed = parse_file(pdf)
    assert parsed["ok"] and not parsed["is_scanned"], f"PDF解析异常: {parsed['error']}"
    assert len(parsed["pages"]) == 3
    assert "380" in parsed["pages"][1], "PDF 文字提取失败（中文未正确写入）"
    print("PDF解析 OK（3页，中文文字层正常）")

    from bidbrief.scanner import scan_folder
    files = scan_folder(tmp, [".pdf"], recursive=True)
    out = os.path.join(tmp, "out")
    print("开始调用 DeepSeek 抽取（约1-2分钟）...")
    result = run_and_export(cfg, files, out, on_log=lambda m: print("  |", m))

    frs = [f for f in result["file_results"]]
    ok_files = [f for f in frs if f["status"].startswith("完成")]
    if not ok_files:
        print("[SELFTEST FAIL] 没有成功处理的文件：")
        for f in frs:
            print(f"   {f['path']} -> {f['status']}")
        return False

    fr = ok_files[0]
    cats = fr["categories"]
    print("\n==== 抽取结果摘要 ====")
    failed = []
    for cat, keywords in EXPECTED.items():
        items = cats.get(cat, [])
        joined = " ".join(
            str(v) for it in items for v in it.values() if isinstance(v, str)
        )
        missing = [k for k in keywords if k not in joined]
        status = "OK" if not missing else f"缺失关键词 {missing}"
        print(f"  {cat}: {len(items)}条 -> {status}")
        if missing:
            failed.append((cat, missing))

    print("\n==== 页码定位抽查（应精确到 1/2/3 页）====")
    for cat in ("废标项", "时间节点", "评分标准"):
        for it in cats.get(cat, [])[:3]:
            label = it.get("页码", "?")
            quote = (it.get("原文摘录", "") or "")[:30]
            print(f"  [{cat}] 第{label}页 | {quote}")
    if cats.get("废标项"):
        p = cats["废标项"][0].get("页码")
        if str(p) != "3":
            print(f"  注意：废标项首条页码为 {p}，预期 3（若为其他页码请人工核对）")

    exports = result.get("exports", {})
    print("\n==== 导出文件 ====")
    # All four formats are generated by default; every path must exist.
    expected_keys = ("excel", "word", "ppt", "markdown", "raw_dir")
    for k in expected_keys:
        v = exports.get(k)
        exists = (os.path.exists(v) if isinstance(v, str) else os.path.isdir(v)) if v else False
        print(f"  {k}: {v} ({'存在' if exists else '缺失!'})")
        if not exists:
            failed.append((k, "文件未生成"))

    if failed:
        print(f"\n[SELFTEST FAIL] {failed}")
        return False
    print("\n[SELFTEST PASS] 端到端流程全部通过。")
    return True


if __name__ == "__main__":
    sys.exit(0 if run_selftest() else 1)
